# -*- coding: utf-8 -*-
"""TubesDatmin_Kelompok2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15a1MfPi8iTt1B1hwKnn7DE5QeuFj5fFl

-------------------------------------------------------------------------------------

# **Tugas Besar Data Mining_Kelompok 2_S1SI-07-C**

Dosen Pengampu : Siti Khomsah, S.Kom., M.Cs.

Anggota Kelompok 2 :
1. Marsya Valeria (2311103105)
2. Najwa Darmawan (2311103108)
3. Shahifah Sajadiyah (2311103116)
4. Geordy Sipho Samuel Damanik (2311103112)

-------------------------------------------------------------------------------------

# **Early Stage Diabetes Prediction**

-------------------------------------------------------------------------------------

# **Judul : "Penerapan Algoritma Klasifikasi Data Mining untuk Prediksi Dini Risiko Diabetes pada Pasien RS Diabetes Sylhet, Bangladesh"**

**Tentang Data :**

Dataset ini didapatkan dari Website Kaggle, dimana dataset ini berisi data tanda dan gejala pasien diabetes baru atau calon pasien diabetes. Data ini dikumpulkan menggunakan kuesioner langsung dari pasien Rumah Sakit Diabetes Sylhet di Sylhet, Bangladesh dan telah disetujui oleh seorang dokter.

**Fitur dataset :**

Dataset ini terdiri dari total 16 fitur dan satu variabel target bernama kelas.

1. Age: Age in years ranging from (20 years to 65 years)
2. Gender: Male / Female
3. Polyuria: Yes / No
4. Polydipsia: Yes/ No
5. Sudden weight loss: Yes/ No
6. Weakness: Yes/ No
7. Polyphagia: Yes/ No
8. Genital Thrush: Yes/ No
9. Visual blurring: Yes/ No
10. Itching: Yes/ No
11. Irritability: Yes/No
12. Delayed healing: Yes/ No
13. Partial Paresis: Yes/ No
14. Muscle stiffness: yes/ No
15. Alopecia: Yes/ No
16. Obesity: Yes/ No

Class: Positive / Negative

-------------------------------------------------------------------------------------

# **Menghubungkan Google Colab dengan Google Drive**
"""

from google.colab import drive
drive.mount('/content/drive')

"""# 1. Load Dataset & Libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder, MinMaxScaler
from google.colab import drive

# ======================================================================
# 1. LOAD DATASET
# ======================================================================

# Untuk Baca file CSV dari Google Drive
data = pd.read_csv("diabetes_data_upload.csv")

"""# 2. Data Exploration

Ketepatan penggunaan statistika deskriptif (grafik & ukuran
statistik) serta mendeskripsikan hasil dari analisis statistika
deskriptif untuk mengetahui karakteristik awal dari dataset
yang digunakan
"""

# ======================================================================
# 2. DATA EXPLORATION
# ======================================================================

st.subheader("🔍 Data Exploration")

# 2.1 Informasi umum dataset
st.header("Data Exploration")

old_stdout = sys.stdout
sys.stdout = buffer = StringIO()

print("Jumlah baris:", data.shape[0])
print("Jumlah kolom:", data.shape[1])
print("Nama kolom:", data.columns.tolist())
print(data.dtypes)
print(data.head())

sys.stdout = old_stdout
st.text(buffer.getvalue())

# 2.2 Identifikasi missing values
st.markdown("### ❗ Missing Values")

missing_count = data.isnull().sum()
missing_percent = (data.isnull().mean() * 100).round(2)

st.markdown("**Jumlah Missing Value per Kolom:**")
st.dataframe(missing_count.rename("Missing Count"))

st.markdown("**Persentase Missing Value per Kolom (%):**")
st.dataframe(missing_percent.rename("Missing Percentage (%)"))

# 2.3 Pisahkan kolom numerik & kategorik
st.markdown("### Tipe Atribut")

numerical_cols = data.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = data.select_dtypes(include=['object']).columns.tolist()

st.write("**Kolom Numerik:**", numerical_cols)
st.write("**Kolom Kategorik:**", categorical_cols)

# 2.4 Statistik deskriptif variabel numerik
st.markdown("### Statistik Deskriptif Variabel Numerik")

desc_num = data[numerical_cols].describe().T
st.dataframe(desc_num)

median_vals = data[numerical_cols].median()
st.markdown("**Median Setiap Variabel Numerik:**")
st.dataframe(median_vals.rename("Median"))

# 2.5 Deteksi outlier dengan IQR
st.markdown("### Deteksi Outlier (Metode IQR)")

Q1 = data[numerical_cols].quantile(0.25)
Q3 = data[numerical_cols].quantile(0.75)
IQR = Q3 - Q1

outlier_mask = (data[numerical_cols] < (Q1 - 1.5 * IQR)) | (data[numerical_cols] > (Q3 + 1.5 * IQR))
outlier_count = outlier_mask.sum()

st.markdown("**Jumlah Outlier per Kolom Numerik:**")
st.dataframe(outlier_count.rename("Outlier Count"))

"""# 3. Data Preparation & Preproccesing

Kualitas tahap cleaning data. Pembersihan data seperti
mengatasi missing values, memperbaiki atau
menghilangkan outliers, melakukan encoding untuk data
kategorikal bila diperlukan, serta standarisasi atau
normalisasi data jika dibutuhkan.
"""

# ======================================================================
# 3. DATA PREPARATION & PREPROCESSING
# ======================================================================

st.subheader("Data Preparation & Preprocessing")

# 1. Handling Missing Value
if data.isnull().values.any():
    data = data.dropna()
    st.success("✅ Poin 1: Missing Value telah dihapus.")
else:
    st.success("✅ Poin 1: Tidak ada missing value.")

# 2. Data Cleaning & Encoding
le = LabelEncoder()
for col in data.columns:
    if data[col].dtype == 'object':
        data[col] = le.fit_transform(data[col])
st.success("✅ Poin 2: Data Cleaning (Encoding) selesai.")

# 3. Deteksi & Handling Outlier (Kolom Age)
Q1 = data['Age'].quantile(0.25)
Q3 = data['Age'].quantile(0.75)
IQR = Q3 - Q1

data = data[
    (data['Age'] >= (Q1 - 1.5 * IQR)) &
    (data['Age'] <= (Q3 + 1.5 * IQR))
]
st.success("✅ Poin 3: Outlier pada kolom Age telah ditangani (IQR Method).")

# 4. Data Reduction (Hapus Duplikat)
before = len(data)
data = data.drop_duplicates()
after = len(data)
st.success(f"✅ Poin 4: Data Reduction selesai. Data berkurang dari {before} menjadi {after} baris.")

# 5. Data Normalization / Scaling
X = data.drop('class', axis=1)
y = data['class']

scaler = StandardScaler()
X_scaled = pd.DataFrame(
    scaler.fit_transform(X),
    columns=X.columns,
    index=X.index
)
st.success("✅ Poin 5: Normalization (Scaling) selesai.")

# 6. Sampling (Data Splitting)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
st.success(
    f"✅ Poin 6: Sampling selesai (80:20). "
    f"Data Latih: {len(X_train)} | Data Uji: {len(X_test)}"
)

# 7. Encoding Data Kategorikal (Langkah Tambahan Sesuai Kode Asli)
columns_to_encode = data.select_dtypes(include=['object']).columns
le = LabelEncoder()

for col in columns_to_encode:
    data[col] = le.fit_transform(data[col])

st.success("✅ Poin 7: Encoding tambahan selesai. Semua data bertipe numerik.")

# 8. Standarisasi Data (Scaling)
X = data.drop('class', axis=1)
y = data['class']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

st.success("✅ Poin 8: Standarisasi data selesai.")

st.markdown("**Preview Data Setelah Preprocessing:**")
st.dataframe(X_scaled.head())


"""# 4. Modelling dan Evaluation (Supervised Learning)

Ketepatan penerapan algoritma, pemilihan hyperparameter awal, dan interpretasi.




4.1 Analisis Regresi Logistik :

- Ketepatan menjelaskan interpretasi koefisien model (baik untuk variabel diskrit maupun kontinu)

- ketepatan menjelaskan variabel signifikan berdasarkan nilai p-value

- ketepatan menjelaskan goodness of fit dari model (berdasarkan nilai Rsquare atau ROC-AUC Curve)

- ketepatan interpretasi hasil evaluasi (confusion matrix -> akurasi, presisi, recall, f1-score)
"""

# ======================================================================
# 4. Modelling
# ======================================================================
import streamlit as st
import sys
from io import StringIO
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, roc_curve, roc_auc_score, accuracy_score, precision_score, recall_score, f1_score
import statsmodels.api as sm

# 4.1 Visualisasi Heatmap Korelasi
print("--- 1. EKSPLORASI HUBUNGAN (HEATMAP) ---")
plt.figure(figsize=(12, 8))
sns.heatmap(data.corr(), annot=True, fmt='.2f', cmap='RdYlGn', linewidths=0.5)
plt.title('Heatmap Korelasi Seluruh Gejala', fontsize=15)
plt.show() # Menutup plot agar tidak menumpuk ke bawah
print("\n" + "="*50 + "\n")

# 4.2 Histogram untuk semua kolom numerik dalam bentuk subplot grid
print("--- 2. HISTOGRAM UNTUK SEMUA KOLOM NUMERIK ---")

    # Pastikan numerical_cols sudah didefinisikan dengan benar
numerical_cols = data.select_dtypes(include=['int64', 'float64']).columns.tolist()
print(f"Kolom numerik yang ditemukan: {numerical_cols}")
print(f"Jumlah kolom numerik: {len(numerical_cols)}")

    # Hanya tampilkan jika ada lebih dari 1 kolom numerik
if len(numerical_cols) > 1:
    n_cols = len(numerical_cols)

    # Tentukan layout grid (4 kolom per baris)
    n_cols_grid = 4
    n_rows_grid = (n_cols + n_cols_grid - 1) // n_cols_grid

    # Buat figure dengan subplot
    fig, axes = plt.subplots(n_rows_grid, n_cols_grid, figsize=(20, n_rows_grid * 4))

    # Jika hanya 1 baris, axes tidak berbentuk array 2D
    if n_rows_grid == 1:
        axes = axes.reshape(1, -1)

    axes = axes.flatten()

    # Loop untuk setiap kolom numerik
    for idx, col in enumerate(numerical_cols):
        sns.histplot(data[col], bins=30, kde=False, color='steelblue',
                    edgecolor='black', ax=axes[idx])
        axes[idx].set_title(col, fontsize=12, fontweight='bold')
        axes[idx].set_xlabel('')
        axes[idx].set_ylabel('Frekuensi' if idx % n_cols_grid == 0 else '')
        axes[idx].grid(axis='y', alpha=0.3, linestyle='--', linewidth=0.5)

    # Sembunyikan subplot yang tidak terpakai
    for idx in range(n_cols, len(axes)):
        axes[idx].set_visible(False)

    plt.suptitle('Histogram Kolom Numerik', fontsize=18, fontweight='bold', y=0.995)
    plt.tight_layout()
    plt.show()
else:
    print(f"Dataset hanya memiliki {len(numerical_cols)} kolom numerik. Histogram grid memerlukan minimal 2 kolom numerik.")


# 4.3 Sinkronisasi index dan pembagian dataset
X_scaled.index = y.index
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# 4.4 Pelatihan model Logistic Regression
X_train_sm = sm.add_constant(X_train)
model_logit = sm.Logit(y_train, X_train_sm).fit(disp=0)

logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
y_prob = logreg.predict_proba(X_test)[:, 1]

print("✅ Model berhasil dilatih.")
print("\n" + "="*50 + "\n")


# 4.5 Feature Importance
print("--- ANALISIS PENGARUH GEJALA (FEATURE IMPORTANCE) ---")
importance = np.abs(logreg.coef_[0])
feat_importances = pd.Series(importance, index=X.columns).sort_values(ascending=True)
plt.figure(figsize=(10, 6))
feat_importances.plot(kind='barh', color='teal')
plt.title('Urutan Gejala Paling Berpengaruh Terhadap Diabetes', fontsize=14)
plt.xlabel('Tingkat Kepentingan (Absolut Koefisien)')
plt.show()

# 4.6 Interpretasi Koefisien
print("\n--- KRITERIA 1: INTERPRETASI KOEFISIEN ---")
coef_df = pd.DataFrame(model_logit.params, columns=['Coefficient'])
print(coef_df)
print("\nInterpretasi:")
print("- Koefisien (+) : Meningkatkan peluang terdiagnosa Diabetes.")
print("- Koefisien (-) : Menurunkan peluang terdiagnosa Diabetes.")

# 4.7 Uji Signifikansi (P-Value)
print("\n--- KRITERIA 2: VARIABEL SIGNIFIKAN (P-VALUE < 0.05) ---")
p_values = model_logit.pvalues
significant_vars = p_values[p_values < 0.05].sort_values()
print(significant_vars)
print("\n" + "="*50 + "\n")


# ======================================================================
# 5. EVALUASI PERFORMA
# ======================================================================

# 5.1 GOODNESS OF FIT
print("--- VALIDASI MODEL (GOODNESS OF FIT) ---")
print(f"Pseudo R-Squared: {model_logit.prsquared:.4f}")
print(f"ROC-AUC Score   : {roc_auc_score(y_test, y_prob):.4f}")

# 5.2 Plot Kurva ROC
fpr, tpr, _ = roc_curve(y_test, y_prob)
plt.figure(figsize=(6, 5))
plt.plot(fpr, tpr, color='red', lw=2, label=f'AUC = {roc_auc_score(y_test, y_prob):.2f}')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
plt.title('Goodness of Fit: ROC Curve')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.legend(loc='lower right')
plt.show()

# 5.3 Confusion Matrix
print("\n--- EVALUASI AKHIR (CONFUSION MATRIX) ---")
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Negatif', 'Positif'], yticklabels=['Negatif', 'Positif'])
plt.title('Confusion Matrix')
plt.xlabel('Prediksi')
plt.ylabel('Aktual')
plt.show()

# 5.4 Metrik Evaluasi
print("\n--- METRIK EVALUASI ---")
print(f"Akurasi  : {accuracy_score(y_test, y_pred):.4f}")
print(f"Presisi  : {precision_score(y_test, y_pred):.4f}")
print(f"Recall   : {recall_score(y_test, y_pred):.4f}")
print(f"F1-Score : {f1_score(y_test, y_pred):.4f}")

# 5.5 Interpretasi Akhir
print("\n--- INTERPRETASI AKHIR ---")
print(f"Model berhasil mengklasifikasikan {cm[1,1]} pasien Positif dengan benar (True Positive)")
print(f"dan {cm[0,0]} pasien Negatif dengan benar (True Negative).")

"""# Dashboard"""

!pip install pyngrok

!ngrok config add-authtoken 37mawMdhRIewqx1CkAl65qd0DtQ_4bMaPYp4e5DQpTosHu9VC

!pip install streamlit

!import streamlit as st

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# from sklearn.preprocessing import LabelEncoder, StandardScaler
# from sklearn.linear_model import LogisticRegression
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import accuracy_score, roc_curve, roc_auc_score
# 
# # ==========================================
# # 1. STATUS AWAL & KONFIGURASI
# # ==========================================
# st.set_page_config(page_title="Diabetes AI System", layout="wide")
# 
# if 'theme' not in st.session_state:
#     st.session_state.theme = 'light'
# if 'lang' not in st.session_state:
#     st.session_state.lang = 'ID'
# 
# def toggle_theme():
#     st.session_state.theme = 'dark' if st.session_state.theme == 'light' else 'light'
# 
# def toggle_lang():
#     st.session_state.lang = 'EN' if st.session_state.lang == 'ID' else 'ID'
# 
# # Shortcut variabel bahasa untuk mempermudah logika
# en = st.session_state.lang == 'EN'
# 
# # ==========================================
# # 2. TEMA DINAMIS
# # ==========================================
# if st.session_state.theme == 'dark':
#     bg_color, card_bg, text_color, border_color = "#0F172A", "#1E293B", "#FFFFFF", "#334155"
#     desc_bg, desc_text = "#111827", "#CBD5E1"
#     plotly_template = "plotly_dark"
# else:
#     bg_color, card_bg, text_color, border_color = "#F1F5F9", "#FFFFFF", "#1E293B", "#E2E8F0"
#     desc_bg, desc_text = "#F8FAFC", "#475569"
#     plotly_template = "plotly_white"
# 
# st.markdown(f"""
#     <style>
#     [data-testid="stAppViewContainer"] {{ background-color: {bg_color} !important; }}
#     [data-testid="stSidebar"] {{ background-color: {card_bg}; border-right: 1px solid {border_color}; }}
# 
#     /* Perbaikan Font Tombol Navigasi agar kontras sesuai Mode */
#     .stButton>button {{
#         color: {text_color} !important;
#         border: 1px solid {border_color} !important;
#         background-color: {card_bg} !important;
#         border-radius: 10px;
#         font-weight: 600;
#     }}
# 
#     h1, h2, h3, h4, p, span, label, .stMarkdown {{ color: {text_color} !important; }}
# 
#     .white-card {{
#         background: {card_bg};
#         border-radius: 20px;
#         padding: 25px;
#         border: 1px solid {border_color};
#         margin-bottom: 20px;
#     }}
# 
#     .chart-desc {{
#         font-size: 14px;
#         color: {desc_text} !important;
#         margin-top: 15px;
#         background: {desc_bg};
#         border-radius: 12px;
#         padding: 15px;
#         border-left: 5px solid #3B82F6;
#     }}
#     </style>
#     """, unsafe_allow_html=True)
# 
# # ==========================================
# # 3. DATA ENGINE
# # ==========================================
# @st.cache_data
# def load_and_train():
#     df = pd.read_csv("/content/drive/My Drive/TubesDataMining_Kelompok 2/diabetes_data_upload.csv")
#     df = df.dropna()
#     df_raw = df.copy()
#     le = LabelEncoder()
#     df_encoded = df.copy()
#     for col in df_encoded.columns:
#         if df_encoded[col].dtype == 'object':
#             df_encoded[col] = le.fit_transform(df_encoded[col])
#     X = df_encoded.drop('class', axis=1)
#     y = df_encoded['class']
#     scaler = StandardScaler()
#     X_scaled = scaler.fit_transform(X)
#     X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
#     model = LogisticRegression().fit(X_train, y_train)
#     return df_raw, df_encoded, model, X_test, y_test, scaler, X.columns
# 
# df_raw, df_encoded, logreg, X_test, y_test, scaler, feature_names = load_and_train()
# y_pred = logreg.predict(X_test)
# y_prob = logreg.predict_proba(X_test)[:, 1]
# 
# 
# # Penerjemah keputusan AI
# def get_risk_level(prob):
#     if prob < 0.3:
#         return "LOW RISK", "#10B981"
#     elif prob < 0.6:
#         return "MEDIUM RISK", "#F59E0B"
#     else:
#         return "HIGH RISK", "#EF4444"
# 
# def explain_prediction(input_data, feature_names, model, top_n=5):
#     contributions = input_data * model.coef_[0]
#     df_exp = pd.DataFrame({
#         "Feature": feature_names,
#         "Contribution": contributions
#     })
#     df_exp["Abs"] = df_exp["Contribution"].abs()
#     return df_exp.sort_values("Abs", ascending=False).head(top_n)
# 
# 
# # ==========================================
# # 4. TOP NAVIGATION
# # ==========================================
# 
# # --- TOP INFO BAR  ---
# st.markdown(f"""
#     <div style="
#         background: linear-gradient(90deg, #1e3a8a, #3b82f6);
#         color: white;
#         padding: 5px 20px;
#         border-radius: 10px;
#         font-size: 12px;
#         display: flex;
#         justify-content: space-between;
#         align-items: center;
#         margin-bottom: 20px;
#     ">
#         <span>🌐 <b>Status:</b> {"AI Model Ready" if en else "Sistem AI Siap"}</span>
#         <marquee scrollamount="5" style="width: 60%; font-style: italic;">
#             {"Penting: Hasil deteksi AI ini bersifat skrining awal, bukan diagnosa pengganti tenaga medis profesional." if not en else "Important: This AI detection result is a preliminary screening, not a substitute for professional medical diagnosis."}
#         </marquee>
#         <span>📅 {pd.Timestamp.now().strftime('%d %B %Y')}</span>
#     </div>
# """, unsafe_allow_html=True)
# 
# # 1. CSS untuk membuat Header melayang dan tombol tetap di atas
# st.markdown(f"""
#     <style>
#     /* Mengunci baris pertama (Header & Tombol) agar tetap di atas saat scroll */
#     div[data-testid="stColumn"]:has(button) {{
#         position: sticky;
#         top: 1rem;
#         z-index: 1000;
#     }}
# 
#     /* Memberikan latar belakang sedikit transparan agar tidak menabrak konten di bawahnya */
#     header[data-testid="stHeader"] {{
#         background-color: rgba(0,0,0,0) !important;
#     }}
# 
#     /* Efek hover pada judul untuk kesan interaktif */
#     .main-title:hover {{
#         transform: scale(1.01);
#         transition: 0.3s;
#     }}
#     </style>
#     """, unsafe_allow_html=True)
# 
# # 2. Struktur Tombol dengan Logo Hospital
# header_col, btn_col = st.columns([4, 2])
# 
# with header_col:
#     title_text = "Advanced Diabetes Early Detection System" if en else "Sistem Deteksi Dini Diabetes AI"
#     # Menggabungkan Logo 🏥 dengan Judul dalam satu baris rapi
#     st.markdown(f"""
#         <div class="main-title" style="display: flex; align-items: center; gap: 15px;">
#             <span style="font-size: 45px;">🏥</span>
#             <h2 style="margin: 0; line-height: 1.2;">{title_text}</h2>
#         </div>
#     """, unsafe_allow_html=True)
# 
# with btn_col:
#     with st.container():
#         c1, c2 = st.columns(2)
# 
#         # Logika Label Tombol Mode
#         theme_label = ("☀️ Light" if en else "☀️ Siang") if st.session_state.theme == 'dark' else ("🌙 Dark" if en else "🌙 Malam")
# 
#         # Logika Label Tombol Bahasa
#         if st.session_state.lang == 'ID':
#             lang_label = "US English"
#         else:
#             lang_label = "ID Indonesia"
# 
#         c1.button(theme_label, on_click=toggle_theme, key="btn_theme_float", use_container_width=True)
#         c2.button(lang_label, on_click=toggle_lang, key="btn_lang_float", use_container_width=True)
# 
# 
# # ==========================================
# # 5. SIDEBAR
# # ==========================================
# 
# # --- TAMBAHAN DI SIDEBAR ---
# st.markdown("---")
# 
# # 1. Lokasi Operasional (Simulasi)
# st.markdown(f"**📍 {"Operational Unit" if en else "Unit Operasional"}**")
# st.caption("General Hospital Center - AI Lab")
# 
# # 2. Model Confidence Score (Menggunakan data AUC yang sudah dihitung)
# auc_val = roc_auc_score(y_test, y_prob) # Pastikan variabel ini tersedia
# st.markdown(f"**🎯 {"Model Reliability" if en else "Keandalan Model"}**")
# st.progress(auc_val)
# st.caption(f"AUC Score: {auc_val:.4f} (Excellent)")
# 
# st.markdown("---")
# 
# # 3. Tips Kesehatan Dinamis
# st.markdown(f"**💡 {"Daily Health Tip" if en else "Tips Kesehatan"}**")
# tips = [
#     "Jaga berat badan ideal untuk mengurangi beban kerja pankreas.",
#     "Perbanyak konsumsi serat dari sayuran hijau.",
#     "Lakukan olahraga rutin minimal 150 menit per minggu.",
#     "Kurangi konsumsi minuman berpemanis buatan."
# ] if not en else [
#     "Maintain ideal body weight to reduce pancreatic workload.",
#     "Increase fiber intake from green vegetables.",
#     "Exercise regularly for at least 150 minutes per week.",
#     "Reduce consumption of artificially sweetened drinks."
# ]
# import random
# st.info(random.choice(tips))
# 
# 
#     # Header Sidebar: Logo & Nama Aplikasi Ringkas
# with st.sidebar:
#     st.markdown(f"""
#         <div style="text-align: center; padding-bottom: 10px;">
#             <img src="https://cdn-icons-png.flaticon.com/512/822/822118.png" width="70">
#             <h4 style='margin-top:10px; color:{text_color} !important;'>
#                 {"Diabetes AI System" if en else "Sistem AI Diabetes"}
#             </h4>
#         </div>
#     """, unsafe_allow_html=True)
# 
#     st.markdown("---")
# 
#     # Menu Navigasi
#     menu_opt = ["Main Dashboard", "Analysis Detail"] if en else ["Dashboard Utama", "Detail Analisis"]
#     menu = st.radio("Menu:", menu_opt)
# 
#     st.markdown("---")
# 
#     # WIDGET ST.INFO: Status Data Real-Time & Ringkasan Teknis
#     st.markdown(f"**{"Real-Time Statistics" if en else "Statistik Real-Time"}**")
#     st.info(f"""
#     - **Algorithm:** Logistic Regression
#     - **Features:** 16 Medical Parameters
#     - **Total Data:** {len(df_raw)} Patients
#     - **Status:** Up to Date (Dec 2025)
#     """)
# 
#     # FOOTER KELOMPOK
#     st.write("<br>" * 3, unsafe_allow_html=True)
# 
#     st.markdown(f"""
#         <div style="background-color: {desc_bg}; padding: 15px; border-radius: 12px; border: 1px solid {border_color};">
#             <p style='margin:0; font-size:12px; font-weight:bold; color:#3B82F6;'>Kelompok 2 - S1SI-07-C</p>
#             <p style='margin:0; font-size:11px; font-weight:600; margin-top:5px;'>Members:</p>
#             <ol style='margin:0; padding-left:15px; font-size:10px; opacity:0.8;'>
#                 <li>Marsya Valeria (3105)</li>
#                 <li>Najwa Darmawan (3108)</li>
#                 <li>Shahifah Sajadiyah (3116)</li>
#                 <li>Geordy Sipho Samuel (3112)</li>
#             </ol>
#             <hr style='margin:8px 0; opacity:0.2;'>
#             <p style='margin:0; font-size:10px; opacity:0.6; text-align:center;'>Dosen: Siti Khomsah, S.Kom., M.Cs.</p>
#         </div>
#     """, unsafe_allow_html=True)
# 
# # ==========================================
# # 6. DASHBOARD UTAMA
# # ==========================================
# if menu in ["Dashboard Utama", "Main Dashboard"]:
#     # KPI SECTION
#     k1, k2, k3, k4 = st.columns(4)
#     k1.markdown(f'<div class="white-card" style="text-align:center;"><small>{"Total Data" if en else "Total Data"}</small><br><b style="font-size:22px;">{len(df_raw)}</b></div>', unsafe_allow_html=True)
#     k2.markdown(f'<div class="white-card" style="text-align:center;"><small>{"Positive Cases" if en else "Kasus Positif"}</small><br><b style="font-size:22px; color:#EF4444;">{(df_raw["class"]=="Positive").mean():.1%}</b></div>', unsafe_allow_html=True)
#     k3.markdown(f'<div class="white-card" style="text-align:center;"><small>{"Average Age" if en else "Rerata Usia"}</small><br><b style="font-size:22px;">{df_raw["Age"].mean():.1f}</b></div>', unsafe_allow_html=True)
#     k4.markdown(f'<div class="white-card" style="text-align:center;"><small>{"AI Accuracy" if en else "Akurasi AI"}</small><br><b style="font-size:22px; color:#3B82F6;">{accuracy_score(y_test, y_pred):.1%}</b></div>', unsafe_allow_html=True)
# 
#     v1, v2 = st.columns(2)
#     with v1:
#         st.markdown(f'<div class="white-card"><h4>{"🚻 Gender Composition" if en else "🚻 Komposisi Gender"}</h4>', unsafe_allow_html=True)
#         st.plotly_chart(px.pie(df_raw, names="Gender", hole=0.6, template=plotly_template), use_container_width=True)
#         desc_v1 = "Analysis of patient distribution by gender to identify risks in certain populations." if en else "Analisis sebaran pasien berdasarkan jenis kelamin untuk mengidentifikasi risiko pada populasi tertentu."
#         st.markdown(f'<div class="chart-desc"><b>{"Analysis:" if en else "Analisis:"}</b> {desc_v1}</div>', unsafe_allow_html=True)
#         st.markdown('</div>', unsafe_allow_html=True)
#     with v2:
#         st.markdown(f'<div class="white-card"><h4>{"📈 Age & Diagnosis Distribution" if en else "📈 Distribusi Usia & Diagnosa"}</h4>', unsafe_allow_html=True)
#         st.plotly_chart(px.histogram(df_raw, x="Age", color="class", barmode='group', template=plotly_template), use_container_width=True)
#         desc_v2 = "Frequency of positive/negative cases by age. Peak risks often occur at productive ages." if en else "Frekuensi kasus positif/negatif berdasarkan usia. Risiko puncak sering terjadi pada usia produktif."
#         st.markdown(f'<div class="chart-desc"><b>{"Analysis:" if en else "Analisis:"}</b> {desc_v2}</div>', unsafe_allow_html=True)
#         st.markdown('</div>', unsafe_allow_html=True)
# 
# 
# # ===================================================
# # 7. FITUR ITERAKTIF (ALAT SIMULASI PREDIKSI RISIKO)
# # ===================================================
# 
#     st.markdown(f'<div class="white-card"><h4>{"🩺 AI Predictor (16 Symptoms)" if en else "🩺 AI Prediktor (16 Gejala)"}</h4>', unsafe_allow_html=True)
# 
#     # Label dengan format Inggris (Indonesia)
#     labels = {
#         "Age": "Age (Usia)",
#         "Gender": "Gender (Jenis Kelamin)",
#         "Polyuria": "Polyuria (Sering Kencing)",
#         "Polydipsia": "Polydipsia (Sering Haus)",
#         "SWL": "Sudden Weight Loss (BB Turun)",
#         "Weak": "Weakness (Badan Lemah)",
#         "Polyph": "Polyphagia (Nafsu Makan +)",
#         "Thrush": "Genital Thrush (Jamur Kelamin)",
#         "Blur": "Visual Blurring (Mata Kabur)",
#         "Itch": "Itching (Gatal-gatal)",
#         "Irrit": "Irritability (Gelisah)",
#         "Heal": "Delayed Healing (Luka Lambat)",
#         "Paresis": "Partial Paresis (Otot Lemah)",
#         "Stiff": "Muscle Stiffness (Kaku Otot)",
#         "Alopecia": "Alopecia (Rambut Rontok)",
#         "Obesity": "Obesity (Obesitas)"
#     }
# 
#     # Gunakan FORM tunggal agar tombol tidak duplikat
#     with st.form(key="diabetes_final_form"):
#         f1, f2, f3, f4 = st.columns(4)
# 
#         with f1:
#             age = st.slider(labels["Age"], 10, 90, 40)
#             gen = st.selectbox(labels["Gender"], ["Male", "Female"] if en else ["Pria", "Wanita"])
#             p1 = st.selectbox(labels["Polyuria"], ["No", "Yes"] if en else ["Tidak", "Ya"])
#             p2 = st.selectbox(labels["Polydipsia"], ["No", "Yes"] if en else ["Tidak", "Ya"])
# 
#         with f2:
#             p3 = st.selectbox(labels["SWL"], ["No", "Yes"] if en else ["Tidak", "Ya"])
#             p4 = st.selectbox(labels["Weak"], ["No", "Yes"] if en else ["Tidak", "Ya"])
#             p5 = st.selectbox(labels["Polyph"], ["No", "Yes"] if en else ["Tidak", "Ya"])
#             p6 = st.selectbox(labels["Thrush"], ["No", "Yes"] if en else ["Tidak", "Ya"])
# 
#         with f3:
#             p7 = st.selectbox(labels["Blur"], ["No", "Yes"] if en else ["Tidak", "Ya"])
#             p8 = st.selectbox(labels["Itch"], ["No", "Yes"] if en else ["Tidak", "Ya"])
#             p9 = st.selectbox(labels["Irrit"], ["No", "Yes"] if en else ["Tidak", "Ya"])
#             p10 = st.selectbox(labels["Heal"], ["No", "Yes"] if en else ["Tidak", "Ya"])
# 
#         with f4:
#             p11 = st.selectbox(labels["Paresis"], ["No", "Yes"] if en else ["Tidak", "Ya"])
#             p12 = st.selectbox(labels["Stiff"], ["No", "Yes"] if en else ["Tidak", "Ya"])
#             p13 = st.selectbox(labels["Alopecia"], ["No", "Yes"] if en else ["Tidak", "Ya"])
#             p14 = st.selectbox(labels["Obesity"], ["No", "Yes"] if en else ["Tidak", "Ya"])
# 
#         # Tombol tunggal di bawah form
#         submitted = st.form_submit_button("CHECK RESULTS (CEK HASIL)", use_container_width=True)
# 
#     # Logika Hasil Prediksi (Muncul setelah klik tombol)
#     if submitted:
#         # Konversi input ke angka (0/1)
#         bm = lambda x: 1 if x in ["Yes", "Male", "Ya", "Pria"] else 0
#         input_data = [age, bm(gen), bm(p1), bm(p2), bm(p3), bm(p4), bm(p5), bm(p6), bm(p7), bm(p8), bm(p9), bm(p10), bm(p11), bm(p12), bm(p13), bm(p14)]
# 
#         # Kalkulasi Prediksi
#         prediction_prob = logreg.predict_proba(scaler.transform([input_data]))[0][1]
# 
#         st.markdown("---")
# 
#         # Styling Status
#         status_text = "POSITIVE (POSITIF)" if prediction_prob > 0.5 else "NEGATIVE (NEGATIF)"
#         status_color = "#EF4444" if prediction_prob > 0.5 else "#10B981" # Merah jika positif, Hijau jika negatif
# 
#         # TABEL HASIL
#         st.markdown(f"""
#             <div style="overflow-x:auto;">
#                 <table style="width:100%; border-collapse: collapse; color: {text_color}; border: 1px solid {border_color};">
#                     <tr style="background-color: {desc_bg};">
#                         <th style="padding: 12px; text-align: left; border-bottom: 2px solid {border_color};">Parameter</th>
#                         <th style="padding: 12px; text-align: left; border-bottom: 2px solid {border_color};">Value (Nilai)</th>
#                     </tr>
#                     <tr>
#                         <td style="padding: 10px; border-bottom: 1px solid {border_color}; font-weight: bold;">Prediction Status</td>
#                         <td style="padding: 10px; border-bottom: 1px solid {border_color}; color: {status_color}; font-weight: bold;">{status_text}</td>
#                     </tr>
#                     <tr>
#                         <td style="padding: 10px; border-bottom: 1px solid {border_color}; font-weight: bold;">Probability Risk</td>
#                         <td style="padding: 10px; border-bottom: 1px solid {border_color};">{prediction_prob:.1%}</td>
#                     </tr>
#                     <tr>
#                         <td style="padding: 10px; font-weight: bold;">Analysis Method</td>
#                         <td style="padding: 10px;">Logistic Regression AI</td>
#                     </tr>
#                 </table>
#             </div>
#         """, unsafe_allow_html=True)
# 
#         # Penjelasan Medis dalam Box
#         if prediction_prob > 0.5:
#             st.warning(f"⚠️ **Penjelasan Medis (Medical Explanation)**: Risiko tinggi terdeteksi. Segera konsultasi ke dokter untuk pemeriksaan lebih lanjut.")
#         else:
#             st.success(f"✅ **Penjelasan Medis (Medical Explanation)**: Risiko rendah terdeteksi. Tetap jaga pola makan dan gaya hidup sehat.")
# 
#     st.markdown('</div>', unsafe_allow_html=True)
# 
# 
# 
# # ==========================================
# # 8. DETAIL ANALISIS
# # ==========================================
# else:
#     # --- HEATMAP (Sudah Benar) ---
#     st.markdown(f'<div class="white-card"><h4>{"📊 Correlation Heatmap" if en else "📊 Heatmap Korelasi"}</h4>', unsafe_allow_html=True)
#     st.plotly_chart(px.imshow(df_encoded.corr(), text_auto=".2f", template=plotly_template), use_container_width=True)
#     desc_heat = "Shows the relationship between features. Higher values indicate a stronger link to diabetes." if en else "Menunjukkan hubungan antar fitur. Nilai tinggi menunjukkan keterkaitan kuat dengan diabetes."
#     st.markdown(f'<div class="chart-desc"><b>{"Explanation (Penjelasan):" if en else "Penjelasan (Explanation):"}</b> {desc_heat}</div>', unsafe_allow_html=True)
#     st.markdown('</div>', unsafe_allow_html=True)
# 
#     c1, c2 = st.columns(2)
# 
#     with c1:
#         # --- FEATURE IMPORTANCE ---
#         st.markdown(f'<div class="white-card"><h4>{"🎯 Feature Importance" if en else "🎯 Kepentingan Fitur"}</h4>', unsafe_allow_html=True)
#         imp = pd.DataFrame({'Feature': feature_names, 'Weight': np.abs(logreg.coef_[0])}).sort_values('Weight')
#         st.plotly_chart(px.bar(imp, x='Weight', y='Feature', orientation='h', template=plotly_template), use_container_width=True)
# 
#         # Tambahan Penjelasan Fitur
#         desc_imp = "Identifies which medical symptoms contribute most to the AI's decision. Top bars are the most critical triggers." if en else "Mengidentifikasi gejala medis mana yang paling berkontribusi pada keputusan AI. Batang teratas adalah pemicu paling kritis."
#         st.markdown(f'<div class="chart-desc"><b>{"Explanation (Penjelasan):" if en else "Penjelasan (Explanation):"}</b> {desc_imp}</div>', unsafe_allow_html=True)
#         st.markdown('</div>', unsafe_allow_html=True)
# 
#     with c2:
#         # --- ROC CURVE ---
#         st.markdown(f'<div class="white-card"><h4>{"📈 ROC Curve" if en else "📈 Kurva ROC"}</h4>', unsafe_allow_html=True)
#         fpr, tpr, _ = roc_curve(y_test, y_prob)
#         auc_score = roc_auc_score(y_test, y_prob)
#         fig_roc = px.area(x=fpr, y=tpr, title=f"AUC: {auc_score:.4f}", template=plotly_template)
#         fig_roc.add_shape(type='line', line=dict(dash='dash'), x0=0, x1=1, y0=0, y1=1)
#         st.plotly_chart(fig_roc, use_container_width=True)
# 
#         # Tambahan Penjelasan ROC
#         desc_roc = f"Measures the model's ability to distinguish between classes. An AUC of {auc_score:.2f} indicates excellent predictive power." if en else f"Mengukur kemampuan model untuk membedakan antar kelas. Skor AUC {auc_score:.2f} menunjukkan kekuatan prediksi yang sangat baik."
#         st.markdown(f'<div class="chart-desc"><b>{"Explanation (Penjelasan):" if en else "Penjelasan (Explanation):"}</b> {desc_roc}</div>', unsafe_allow_html=True)
#         st.markdown('</div>', unsafe_allow_html=True)

# Digunakan untuk menjalankan aplikasi Dashboard yang sudah dibuat agar tetap menyala meskipun kamu menutup atau meninggalkan sel kode di Google Colab.
!nohup streamlit run app.py &

# Gunakan perintah ngrok yang biasa Anda pakai, contoh:
from pyngrok import ngrok

# Jika Anda menggunakan authtoken, masukkan dulu:
# ngrok.set_auth_token("TOKEN_ANDA")

# Buka tunnel baru
public_url = ngrok.connect(8501)
print("Klik Link ini untuk membuka Dashboard:", public_url)

# Perintah sistem di Google Colab untuk menghentikan proses aplikasi ngrok yang sedang berjalan di latar belakang.
!pkill ngrok